 node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/srast3/spring-kafka-microservice.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('ConfigServer') {
                def app = docker.build "localhost:5000/config-server:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/config-server:${env.version}").run('-p 8888:8888 -h config-server --name config-server --link discovery')
        }

        stage ('Final') {
            build job: 'email-service-pipeline', wait: false
        }      

    }

}