spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  kafka:
    bootstrap-servers: 172.18.0.3:9092
    topic:
      userRegistered: USER_REGISTERED_TOPIC
security:
  basic:
    enabled: false